//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semesterprojekt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class forumDB : DbContext
    {
        public forumDB()
            : base("name=forumDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UForum> UForums { get; set; }
        public virtual DbSet<UForumCat> UForumCats { get; set; }
        public virtual DbSet<UForumThread> UForumThreads { get; set; }
        public virtual DbSet<UForumTopic> UForumTopics { get; set; }
        public virtual DbSet<UForumTopicReply> UForumTopicReplies { get; set; }
    }
}
