//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semesterprojekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class UForumTopicReply
    {
        public int TopicRId { get; set; }
        public string TopicRTitle { get; set; }
        public string TopicRText { get; set; }
        public Nullable<System.DateTime> TopicRDate { get; set; }
        public Nullable<int> fk_TopicId { get; set; }
        public Nullable<int> fk_UserId { get; set; }
    }
}
