//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semesterprojekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class UForumThread
    {
        public int ThreadId { get; set; }
        public string ThreadName { get; set; }
        public string ThreadText { get; set; }
        public Nullable<System.DateTime> ThreadDate { get; set; }
        public Nullable<int> fk_CatId { get; set; }
        public Nullable<int> fk_UserId { get; set; }
    }
}
