//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semesterprojekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class UForumTopic
    {
        public int TopicId { get; set; }
        public string TopicTitle { get; set; }
        public string TopicText { get; set; }
        public Nullable<System.DateTime> TopicDate { get; set; }
        public Nullable<int> fk_ThreadId { get; set; }
        public Nullable<int> fk_UserId { get; set; }
    }
}
