//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semesterprojekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class UForum
    {
        public int ForumId { get; set; }
        public string ForumName { get; set; }
        public Nullable<System.DateTime> ForumDate { get; set; }
        public Nullable<int> fk_userid { get; set; }
    }
}
